package oasis.task.tech.constants;

public enum UserPermission {
    CAN_CREATE_TASK, CAN_VIEW_TASK, CAN_UPDATE_TASK, CAN_DELETE_TASK,
    CAN_CREATE_USER, CAN_VIEW_USER, CAN_UPDATE_USER, CAN_DELETE_USER,
    CAN_VIEW_ALL_USERS, CAN_VIEW_ALL_TASKS,
}
